// <auto-generated />
using System;
using BlazorServerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerApp.Migrations
{
    [DbContext(typeof(Applicationdbcontext))]
    [Migration("20240917221820_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorServerApp.Models.Departmant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Departmants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("BlazorServerApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("dept_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dept_Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "mohamed@example.com",
                            Name = "Mohamed swelam",
                            dept_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "alaa@example.com",
                            Name = "Mohamed alaa",
                            dept_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            Email = "bahaa@example.com",
                            Name = "Ahmed bahaa",
                            dept_Id = 3
                        });
                });

            modelBuilder.Entity("BlazorServerApp.Models.Student", b =>
                {
                    b.HasOne("BlazorServerApp.Models.Departmant", "departmant")
                        .WithMany("Students")
                        .HasForeignKey("dept_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("departmant");
                });

            modelBuilder.Entity("BlazorServerApp.Models.Departmant", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
